src/Entity/Dossier.php
<?php

namespace App\Entity;

use App\Repository\DossierRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;


/**
 * @ORM\Entity(repositoryClass=DossierRepository::class)
 */
class Dossier
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\OneToMany(targetEntity=Fichier::class, mappedBy="dossier" , cascade={"all"}, orphanRemoval=true )
     */
    private $fichiers;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     * @Assert\NotBlank (message=" entrez la description s'il vous plait !!")
     */
    private $DateCreation;




    public function __construct()
    {
        $this->fichiers = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return Collection|Fichier[]
     */
    public function getFichiers(): Collection
    {
        return $this->fichiers;
    }

    public function addFichier(Fichier $fichier): self
    {
        if (!$this->fichiers->contains($fichier)) {
            $this->fichiers[] = $fichier;
            $fichier->setDossier($this);
        }

        return $this;
    }

    public function removeFichier(Fichier $fichier): self
    {
        if ($this->fichiers->removeElement($fichier)) {
            // set the owning side to null (unless already changed)
            if ($fichier->getDossier() === $this) {
                $fichier->setDossier(null);
            }
        }

        return $this;
    }
    public function __toString()
    {
        return (string) $this->getId();
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getDateCreation(): ?\DateTimeInterface
    {
        return $this->DateCreation;
    }

    public function setDateCreation(\DateTimeInterface $DateCreation): self
    {
        $this->DateCreation = $DateCreation;

        return $this;
    }




}

src/Form/DossierType.php
<?php

namespace App\Form;

use App\Entity\Dossier;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class DossierType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('description', TextareaType::class,
                ['attr'=>['placeholder'=>"description du dossier"]])
            ->add('Ajouter dossier ',SubmitType::class,
                ['attr'=>['formnovalidate'=>'formnovalidate']])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Dossier::class,
        ]);
    }
}

src/Controller/DossierController.php
<?php

namespace App\Controller;

use App\Entity\Dossier;
use App\Form\DossierType;
use App\Repository\DossierRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Validator\Constraints\DateTime;

class DossierController extends AbstractController
{
    /**
     * @Route("/dossier", name="dossier")
     */
    public function index(): Response
    {
        return $this->render('dossier/index.html.twig', [
            'controller_name' => 'DossierController',
        ]);
    }

    /**
     * @Route("/removeD/{id}", name="remove_dossier")
     */
    public function remove($id)
    {
        $dossier = $this->getDoctrine()->getRepository(Dossier::class)->find($id);
        $em = $this->getDoctrine()->getManager();
        $em->remove($dossier);
        $em->flush();
        return $this->redirectToRoute('dossier_show');
    }

    /**
     * @Route("/listdossier", name="dossier_show")
     */
    public function afficheDossier()
    {
        $dossier = $this->getDoctrine()->getRepository(dossier::class)->findAll();
        return $this->render("dossier/ShowDoc.html.twig", array("dossiers" => $dossier));

    }
    /**
     * @Route("/dossier/add", name="dossier_create")
     */
    public function CreerDossier (Request $request){

        $dossier=new Dossier();
        $form=$this->createForm(DossierType::class,$dossier);

        $form->handleRequest($request);
        $dossier->setDateCreation(new \DateTime('now'));


        if($form->isSubmitted()
            //&& $form->isValid()
        )
        {
            $em=$this->getDoctrine()->getManager();
            $em->persist($dossier);
            $em->flush();
            
            mkdir(__DIR__ . '/../../public/uploads/' . $dossier->getDescription());

            return $this->redirectToRoute('dossier_show');
        }
        return $this->render('dossier/create.html.twig' , ['formDossier' =>$form->createView()]);
    }
    /**
     * @Route("/dossier/{id}/edit", name="edit_dossier")
     */
    function UpdateDoc(DossierRepository $repository, $id,Request $request)
    {
        $dossier = $repository->find($id);
        $form = $this->createForm(DossierType::class, $dossier);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($dossier);
            $em->flush();

            return $this->redirectToRoute("dossier_show");


        }
        return $this->render('dossier/UpdateDoc.html.twig', ['form' => $form->createView()]);}

    // /**
    // * @Route("dossier/recherche", name="recherche")
    //  */
    // function Recherche(DossierRepository $repository,Request $request)
    //{
    //   $data=$request->get('search');
    //  $dossier=$repository->findBy(['id'=>$data]);
    //  return $this->render('dossier/ShowDoc.html.twig', array("dossiers" => $dossier));
    // }

}

templates/dossier/ShowDoc.html.twig
{% extends 'baseee.html.twig' %}
{% block title %} {% endblock  %}

{% block body %}
    <div class="m-4">
        <h2 style="color: #22aab1;">Liste des dossiers</h2>
    </div>
    <table class="table table-striped table-hover">
        <thead style="backgournd: #efefef;"> <!-- hedhi yaani table headers -->
        <tr>
            <th>id</th>
            <th>description</th>
            <th>date de creation</th>
            <th>fichiers</th>
            <th>update</th>
            <th>remove</th>
        </tr>
        </thead>
        <tbody> <!-- table body -->

        <br> <br> <br> <br>
        {% for c in dossiers %}
            <tr>
                <td> {{ c.id}}</td>
                <td> {{ c.description}}</td>
                <td> {{ c.dateCreation |date() }}</td>

                <td><a href="{{ path('fichier_show') }}">fichiers</a></td>
                <td><a href="{{ path('edit_dossier',{'id':c.id}) }}">update</a></td>
                <td><a href="{{ path('remove_dossier',{'id':c.id}) }}">Remove</a></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock  %}

templates/dossier/UpdateDoc.html.twig
{% extends 'baseee.html.twig' %}
{% form_theme form 'bootstrap_4_layout.html.twig' %}
{% block body %}

    <h1>modification un dossier</h1>



    {{ form_start(form) }}


    {{ form_widget(form) }}
    <button type="submit" class="btn btn-success" > modifier le dossier</button>
    {{ form_end(form) }}

{% endblock %}

templates/dossier/create.html.twig
{% extends 'baseee.html.twig' %}

{% form_theme formDossier 'bootstrap_4_layout.html.twig' %}

{% block body %}
    <br> <br>
<h1> création d'un dossier</h1>
    <br> <br>


{{ form_start(formDossier) }}
{{ form_widget(formDossier) }}

    {{ form_end(formDossier) }}

{% endblock %}

templates/dossier/index.html.twig
{% extends 'baseee.html.twig' %}

{% block title %} Home{% endblock %}

{% block body %}

{% endblock %}